spring:
  profiles:
    active:
      -dev
---
server:
  port: 8200
spring:
  profiles: dev
  application:
    name: config-client-dev
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: config-client-test
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/